git remote add S1ckick                   https://github.com/S1ckick/spbetu_os_2021_9382.git            # Субботин
git remote add somewaytolive             https://github.com/somewaytolive/spbetu_os_2021_9382.git      # Круглова
git remote add Valentina-Gol             https://github.com/Valentina-Gol/spbetu_os_2021_9382.git      # Голубева
git remote add lastrise                  https://github.com/lastrise/spbetu_os_2021_9382.git           # Русинов
git remote add BabylonExile              https://github.com/BabylonExile/spbetu_os_2021_9382.git       # Михайлов
git remote add dmitryduy                 https://github.com/dmitryduy/spbetu_os_2021_9382.git          # Дерюгин
git remote add VIkDema                   https://github.com/VIkDema/spbetu_os_2021_9382.git            # Демин
git remote add Crunchy0                  https://github.com/Crunchy0/spbetu_os_2021_9382.git           # Павлов
git remote add alexundertable            https://github.com/alexundertable/spbetu_os_2021_9382.git     # Кодуков
git remote add Homry                     https://github.com/Homry/spbetu_os_2021_9382.git              # Сорокумов
git remote add Indiora                   https://github.com/Indiora/spbetu_os_2021_9382.git            # Савельев
git remote add TestGeorgeH               https://github.com/TestGeorgeH/spbetu_os_2021_9382.git        # Герасев
git remote add SonKhwa                   https://github.com/SonKhwa/spbetu_os_2021_9382.git            # Пя
git remote add dmitrikuz                 https://github.com/dmitrikuz/spbetu_os_2021_9382.git          # Кузьмин
git remote add MilanaBalaeva             https://github.com/MilanaBalaeva/spbetu_os_2021_9382.git      # Балаева
git remote add sergeyyurev               https://github.com/sergeyyurev/spbetu_os_2021_9382.git        # Юрьев  
git remote add Ryzhikh-Roman             https://github.com/Ryzhikh-Roman/spbetu_os_2021_9382.git      # Рыжих  
git remote add NereusOcean               https://github.com/NereusOcean/spbetu_os_2021_9382.git        # Иерусалимов
git remote add tehril17                  https://github.com/tehril17/spbetu_os_2021_9382.git           # Докукин 
#git remote add                           https://github.com//spbetu_os_2021_9382.git                  # 
